logging:
  level: INFO
  loggers:
    com.taskmanager.tasker: DEBUG


# Database settings.
database:
  # the name of your JDBC driver
  driverClass: org.h2.Driver

  # the username
  user: sa

  # the password
  password: 

  # the JDBC URL
  url: jdbc:h2:mem:datajpa

  # any properties specific to your JDBC driver:
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.H2Dialect
    hibernate.hbm2ddl.auto: create
    

  # the maximum amount of time to wait on an empty pool before throwing an exception
  maxWaitForConnection: 3s

  # the SQL query to run when validating a connection's liveness
  validationQuery: "/* MyApplication Health Check */ SELECT 1"